[package]
name = "osu-ipc-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpu-endian = "0.1.1"
rosu-pp = "0.7.1"
serde = { version = "1.0.140", features = ["derive"] }
serde_json = "1.0.82"
